# Generated by Django 5.1.11 on 2026-07-28 09:33

import django.db.models.deletion
from django.db import migrations, models

def copy_legacy_neighborhood_names(apps, schema_editor):
    Application = apps.get_model("portal", "Application")
    for application in Application.objects.select_related("neighborhood").filter(
        neighborhood__isnull=False, neighborhood_name=""
    ).iterator():
        application.neighborhood_name = application.neighborhood.name
        application.save(update_fields=["neighborhood_name"])


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='neighborhood_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='application',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.neighborhood'),
        ),
        migrations.RunPython(copy_legacy_neighborhood_names, migrations.RunPython.noop),
    ]
